# Generated by Django 4.1.1 on 2022-09-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100, verbose_name='Nombre')),
                ('eemail', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('econtact', models.CharField(max_length=15, verbose_name='Contacto')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
